version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aivacol-sqlserver
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Aivacol123456!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      # test:
      #   [
      #     "CMD",
      #     '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q ''SELECT 1'' || exit 1',
      #   ]
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Aivacol123456!",
          "-Q",
          "SELECT 1",
          "-C",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - aivacol-net

  sqlserver-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./scripts:/usr/config
    networks:
      - aivacol-net
    command: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'Aivacol123456!' -C -i /usr/config/init.sql
      "
volumes:
  sqlserver-data:

networks:
  aivacol-net:
    driver: bridge
